# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
host: 0.0.0.0

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Logan Crandall - Accidentally Coded
email: logan@accidentallycoded.com
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
sections:
    - name: Home
      anchor: home
    - name: Who am I
      anchor: about
    - name: Projects
      anchor: projects
    - name: Contact Me
      anchor: contact

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
exclude: []

resumelink: "https://docs.google.com/document/d/1fv0njCmxElh1bGPsvHUYBdjvt4Bi_YC9irQrNKXANaU/edit?usp=sharing"
githublink: "https://github.com/link00000000/"
handshakelink: "https://uakron.joinhandshake.com/users/8438281"
twitterlink: "https://twitter.com/@crandall_logan"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
